### ISSUE TITLE
你好我是新手学习中碰到些问题

### ISSUE THREAD

**Issue by toplazy** [davyxu/cellmesh#5]
按照搭建的教程里 运行client的时候碰到些问题 能帮忙看看吗 找不到agent

anic: AgentNotFound

goroutine 1 [running]:
main.login.func1(0xc000314030)
	/Users/zhoumo/go/src/github.com/davyxu/cellmesh/demo/svc/client/main.go:52 +0x19d
reflect.Value.call(0x1465620, 0xc0001670a0, 0x13, 0x1518249, 0x4, 0xc0001abd80, 0x1, 0x1, 0x10a77fb, 0x3b9aca00, ...)
	/usr/local/Cellar/go/1.11.2/libexec/src/reflect/value.go:447 +0x449
reflect.Value.Call(0x1465620, 0xc0001670a0, 0x13, 0xc0001abd80, 0x1, 0x1, 0xc0001ae120, 0x203000, 0x203000)
	/usr/local/Cellar/go/1.11.2/libexec/src/reflect/value.go:308 +0xa4
main.RemoteCall(0x14fdbc0, 0xc00016c900, 0x14f6ee0, 0xc000169f80, 0x1465620, 0xc0001670a0, 0x0, 0x0)
	/Users/zhoumo/go/src/github.com/davyxu/cellmesh/demo/svc/client/clientconn.go:202 +0x4f3
main.login(0xc0001abf48, 0x6, 0x0, 0x0, 0x1)
	/Users/zhoumo/go/src/github.com/davyxu/cellmesh/demo/svc/client/main.go:42 +0x1fb
main.main()
	/Users/zhoumo/go/src/github.com/davyxu/cellmesh/demo/svc/client/main.go:111 +0x119

**Comment by davyxu** [comment]
cellnet 和 cellmesh都更新到最新, 把服务器都重编下
AgentNotFound的意思就是, agent没有把自己的状态信息汇报到hub服务器上, 从login登录, 选不出agent来

**Comment by toplazy** [comment]
我全部都删除了 然后都go get了一遍 还是一样的问题 我再研究下 我肯定是哪一步弄错了 谢谢回答

**Comment by davyxu** [comment]
把hub服启动起来

**Comment by toplazy** [comment]
谢谢谢谢大牛 终于可以run起来了  原来我没注意到还有个hub   
然后我打字 hello就断开连接了 这是正常的吗

**Comment by davyxu** [comment]
输出什么错

**Comment by davyxu** [comment]
进群讨论, 别在github上聊天

**Comment by toplazy** [comment]
啊 有群的吗 群号是啥

**Comment by toplazy** [comment]
找到了 已经申请

**Comment by chenwbyx** [comment]
群在哪儿呀，我有问题
